#General guide:
#
# Directories:
#   Can be specified as relative or absolute path
#   example for absolute path: 'D:\BTFileDownloader\download'
#   example for relative path: 'someDirectory\download'
#
# boolean values:
#   can be either "True" or "False", although "true" and "false" also work (will be automatically replaced when you save the config)
#
# date format:
#   date format will always be yyyy.MM.dd as the alphabetical order will then be the same as the chronological order


#rebind the menu navigation keys, structure is: 'Key: Binding'
#available keys: https://docs.microsoft.com/en-us/dotnet/api/system.consolekey?view=netframework-4.8
#available bindings: up, down, left, right, enter, back
#does not affect text editor!
menuControlMapping:
  W: Up
  UpArrow: Up
  S: Down
  DownArrow: Down
  A: Left
  LeftArrow: Left
  D: Right
  RightArrow: Right
  Enter: Enter
  Backspace: Back
  Escape: Back

#you shouldn't have to change this, but just in case you do, you can
onlineAddressDict:
  RS_DATA: data
  RS_SCENE: scene
  RS_SHARED: shareddata
  RS_SOUND: sound
  RS_MOVIES: movies


#======================================================================================
fileDownloaderConfig:
  #if set to true it will wait for user input when a file throws an exception during downloading
  #if set to false it will ignore all failed downloads apart from logging them
  pauseDownloadOnError: True

  #if set to false it won't download the files and instead only log which files it would download
  doDownload: False

  downloadURL:
    baseURL: http://media.schoolofdragons.com/DWADragonsUnity
    platform: Steam
    version: 3.6.0
    baseSuffix: High
    assetInfo: data/AssetVersionsDO.xml

  outputDirectory:
    baseDirectory: fileDownloads

    #if set to false it will download directly to the baseDirectory
    #if set to true it will append the platform/version/date as subdirectories
    # example:
    #  platform = true, version = false, date = true
    #  will result in
    #  fileDownloads\Steam\2020.04.07
    appendPlatform: False
    appendVersion: False
    appendDate: False

  #use this to filter filenames
  #filterexamples:
  #  allow al files of any directory with a name starting with "dw" and ending with "do" (e.g. 'RS_SHARED/dwthunderdrumdo')
  #    ^(.*?)/dw(.*?)do$
  #
  #  use multiple regex filters (only allows files that match all filters)
  #    regexFilters:
  #      - filter1
  #      - !filter2
  #      - \!filter3
  #
  #  to negate a regex (allowing only files that don't match it) start the filter with an '!' character (see above)
  #  if your regex starts with an '!' for other reasons you can escape the negation by putting a '\' in front of it
  regexFilters:
  - (RS_SOUND/sndwingflapmed7)|(RS_MOVIES/BoD_Intro.mp4)

  #use this to only download some localizations
  #otherwise downloads ALL localizations available
  #filterexamples:
  # allow only en-us and de-de localized files (and files that are not localized)
  #   localeFilters:
  #     - en-us
  #     - de-de
  localeFilters:
  - en-us
  - de-de


#======================================================================================
addressableCompareConfig:
  #defines the config values depending on sourceType
  sourceFrom:
    #can be "online", "local" or "lastcreated"
    sourceType: lastcreated
    online:
      platform: Steam
      version: 3.8.0
      makeFile: true
      #won't do anything if makeFile is set to false (because then there won't be any file in the first place)
      #if makeFile and this are set to true it will register the created file as 'lastcreated' for faster comparisons in the future
      makeLastCreated: false
    local:
      #if you created the files using automatic platform/version/date appending you can specify them here
      #these won't be used if they're set to false in 'sourcesConfig'
      platform: Steam
      version: 3.8.0
      date: 2020.04.07

  sourceTo:
    sourceType: online
    online:
      platform: Steam
      version: 3.8.0
      makeFile: true
      makeLastCreated: true
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07


  #used when your 'sourceType' is 'online'
  onlineSourcesConfig:
    baseURL: http://media.schoolofdragons.com/DWADragonsUnity
    baseSuffix: High
    assetInfo: data/AssetVersionsDO.xml

  #used when you set 'makeFile' to true or your 'sourceType' is 'local'
  localSourcesConfig:
    #basedirectory for local files created by setting 'makeFile' to true in online sources
    baseDirectory: addressablesHistory\sources
    targetFileName: assetInfo
    targetFileExtension: txt
    # you can edit this manually, but I'd recommend utilising makeLastCreated for automatic generation or selecting a file in the editor
    lastcreated: addressablesHistory\sources\assetInfo_2020.04.07.txt
    #as opposed to fileDownloaderConfig.downloadURL this doesn't create subfolders, but appends it to the filename
    #for example: assetInfo_Steam_3.6.0_2020.04.07.txt
    appendPlatform: false
    appendVersion: false
    appendDate: true

  resultConfig:
    #can be set to false to exclusively output results in the terminal
    makeFile: true
    baseDirectory: addressablesHistory\results
    appendDate: true


#======================================================================================
fireballCompareConfig:
  sourceFrom:
    sourceType: lastcreated
    online:
      platform: Steam
      version: 3.8.0
      makeFile: true
      makeLastCreated: false
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07
  
  sourceTo:
    sourceType: online
    online:
      platform: Steam
      version: 3.8.0
      makeFile: true
      makeLastCreated: true
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07

  onlineSourcesConfig:
    baseURL: http://media.schoolofdragons.com/DWADragonsUnity
    baseSuffix: High
    dataContainer: data/dragonsres

  localSourcesConfig:
    baseDirectory: fireballHistory\sources
    targetFileName: fireball
    targetFileExtension: txt
    lastcreated: fireballHistory\sources\fireball_2020.04.09.txt
    #same behaviour as addressableComparer
    appendPlatform: false
    appendVersion: false
    appendDate: true

  resultConfig:
    makeFile: true
    baseDirectory: fireballHistory\results
    appendDate: true

  #I strongly dissuade you from touching this - in theory you could modify this to find different types of data, but that requires exact knowledge of the monobehaviour-structure
  targetStatPath:
  - _Weapons:Weapon
  - Array:Array

  #Basically just an internal value, this defines that the value of '_Name' can be used as a unique key (and makes '_Name' the first result-Column)
  mapStatsBy: _Name

  #set a value to false to ignore it
  statList:
    _Name: true
    _MinSpeed: true
    _MaxTimeToTarget: true
    _Damage: true
    _CriticalDamageMultiplier: true
    _CriticalDamageChance: true
    _Energy: true
    _TouchRadius: true
    _Lifetime: true
    _TotalShots: true
    _Cooldown: true
    _Range: true
    _Homing: true
    _SlowEffect: true
    _AmmoType: true
    _RechargeRange:Min: true
    _RechargeRange:Max: true
    _AvailableShots: true


#======================================================================================
squadTacticsCompareConfig:
  sourceFrom:
    sourceType: lastcreated
    online:
      platform: Steam
      version: 3.8.0
      makeFile: true
      makeLastCreated: false
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07
  
  sourceTo:
    sourceType: online
    online:
      platform: Steam
      version: 3.8.0
      makeFile: true
      makeLastCreated: true
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07

  onlineSourcesConfig:
    baseURL: http://media.schoolofdragons.com/DWADragonsUnity
    baseSuffix: High
    dataContainer: data/dragonsres

  localSourcesConfig:
    baseDirectory: squadTacticsHistory\sources
    targetFileName: squadTactics
    targetFileExtension: txt
    lastcreated: squadTacticsHistory\sources\squadTactics_2020.04.18.txt
    #same behaviour as addressableComparer
    appendPlatform: false
    appendVersion: false
    appendDate: true

  resultConfig:
    makeFile: true
    baseDirectory: squadTacticsHistory\results
    appendDate: true

  #I strongly dissuade you from touching this - in theory you could modify this to find different types of data, but that requires exact knowledge of the monobehaviour-structure
  targetStatPath:
  - _Characters:CharacterData
  - Array:Array

  #Basically just an internal value, this defines that the value of '_Name' can be used as a unique key (and makes '_Name' the first result-Column)
  mapStatsBy: _NameID

  #set a value to false to ignore it (comparison output only, sources will always save all data)
  statList:
    _NameID: true
    _Available: true
    _DisplayNameText:_Text: true
    _DisplayNameText:_ID: true
    _SpeciesText:_Text: true
    _SpeciesText:_ID: true

    _Stats:_CriticalChance:_BaseValue: true
    _Stats:_CriticalChance:_LevelMultiplier: true
    _Stats:_CriticalChance:_LimitMultiplier: true
    _Stats:_CriticalChance:_Limits:Min: true
    _Stats:_CriticalChance:_Limits:Max: true
    _Stats:_CriticalChance:_UseRoundedValues: true

    _Stats:_CriticalDamageMultiplier:_BaseValue: true
    _Stats:_CriticalDamageMultiplier:_LevelMultiplier: true
    _Stats:_CriticalDamageMultiplier:_LimitMultiplier: true
    _Stats:_CriticalDamageMultiplier:_Limits:Min: true
    _Stats:_CriticalDamageMultiplier:_Limits:Max: true
    _Stats:_CriticalDamageMultiplier:_UseRoundedValues: true

    _Stats:_DodgeChance:_BaseValue: true
    _Stats:_DodgeChance:_LevelMultiplier: true
    _Stats:_DodgeChance:_LimitMultiplier: true
    _Stats:_DodgeChance:_Limits:Min: true
    _Stats:_DodgeChance:_Limits:Max: true
    _Stats:_DodgeChance:_UseRoundedValues: true

    _Stats:_FirePower:_BaseValue: true
    _Stats:_FirePower:_LevelMultiplier: true
    _Stats:_FirePower:_LimitMultiplier: true
    _Stats:_FirePower:_Limits:Min: true
    _Stats:_FirePower:_Limits:Max: true
    _Stats:_FirePower:_UseRoundedValues: true

    _Stats:_HealingPower:_BaseValue: true
    _Stats:_HealingPower:_LevelMultiplier: true
    _Stats:_HealingPower:_LimitMultiplier: true
    _Stats:_HealingPower:_Limits:Min: true
    _Stats:_HealingPower:_Limits:Max: true
    _Stats:_HealingPower:_UseRoundedValues: true

    _Stats:_Health:_BaseValue: true
    _Stats:_Health:_LevelMultiplier: true
    _Stats:_Health:_LimitMultiplier: true
    _Stats:_Health:_Limits:Min: true
    _Stats:_Health:_Limits:Max: true
    _Stats:_Health:_UseRoundedValues: true

    _Stats:_Movement:_BaseValue: true
    _Stats:_Movement:_LevelMultiplier: true
    _Stats:_Movement:_LimitMultiplier: true
    _Stats:_Movement:_Limits:Min: true
    _Stats:_Movement:_Limits:Max: true
    _Stats:_Movement:_UseRoundedValues: true

    _Stats:_Strength:_BaseValue: true
    _Stats:_Strength:_LevelMultiplier: true
    _Stats:_Strength:_LimitMultiplier: true
    _Stats:_Strength:_Limits:Min: true
    _Stats:_Strength:_Limits:Max: true
    _Stats:_Strength:_UseRoundedValues: true


#======================================================================================
flightStatsCompareConfig:
  sourceFrom:
    sourceType: lastcreated
    online:
      platform: Steam
      version: 3.8.0
      makeFile: true
      makeLastCreated: false
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07

  sourceTo:
    sourceType: online
    online:
      platform: Steam
      version: 3.8.0
      makeFile: true
      makeLastCreated: true
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07

  onlineSourcesConfig:
    baseURL: http://media.schoolofdragons.com/DWADragonsUnity
    baseSuffix: High
    assetInfo: data/AssetVersionsDO.xml
    dataContainerRegexFilters:
    - "^RS_SHARED/dw(.*?)do$"
    - "!^RS_SHARED/dwdragonsskins(.*?)do$"
    - "!^RS_SHARED/dw(.*?)(common|rare|epic|(legend(ary)?))do$"
    - "!^RS_SHARED/dwshieldrounddo$"
    - "!^RS_SHARED/dw(.*?)(saddle)(s?)do$"

  localSourcesConfig:
    baseDirectory: flightStatsHistory\sources
    targetFileName: flightStats
    targetFileExtension: txt
    lastcreated: flightStatsHistory\sources\flightStats_2020.04.18.txt
    appendPlatform: false
    appendVersion: false
    appendDate: true

  resultConfig:
    makeFile: true
    baseDirectory: flightStatsHistory\results
    appendDate: true

  #note: searchpattern can not be modified here,
  #  because the search requires multiple interdependent files and spending hours on a generic config system would not be worth it

  flightTypesDict:
    0: Flying
    1: Gliding
    2: Racing

  #set a value to false to ignore it (comparison output only, sources will always save all data)
  statList:
    _RollTurnRate: true
    _RollDampRate: true
    _YawTurnRate: true
    _YawTurnFactor: true
    _PitchTurnRate: true
    _PitchDampRate: true
    _Speed:_Min: true
    _Speed:_Max: true
    _Acceleration: true
    _ManualFlapAccel: true
    _ManualFlapTimer: true
    _SpeedDampRate: true
    _BrakeDecel: true
    _ClimbAccelRate: true
    _DiveAccelRate: true
    _SpeedModifierOnCollision: true
    _BounceOnCollision: true
    _GlideDownMultiplier: true
    _GravityModifier: true
    _GravityClimbMultiplier: true
    _GravityDiveMultiplier: true
    _FlyingMaxUpPitch: true
    _FlyingMaxDownPitch: true
    _GlidingMaxUpPitch: true
    _GlidingMaxDownPitch: true
    _MaxRoll: true
    _FlyingPositionBoostFactor: true


#======================================================================================
timedMissionCompareConfig:
