#General guide:
#
# Directories:
#   Can be specified as relative or absolute path
#   example for absolute path: 'D:\BTFileDownloader\download'
#   example for relative path: 'someDirectory\download'
#
# boolean values:
#   can be either "True" or "False", although "true" and "false" also work (will be automatically replaced when you save the config)
#
# date format:
#   date format will always be yyyy.MM.dd as the alphabetical order will then be the same as the chronological order

coreConfigPath: config/coreConfig.yaml

subPrograms:
- !!fileDownloader
  configFilePath: config/fileDownloader.yaml
  programName: FileDownloader
  runText: Run Download
  backText: Back to Main Menu

- !!comparer
  configFilePath: config/addressableComparer.yaml
  programName: AddressableComparer
  runText: Run Comparison
  backText: Back to Main Menu

- !!comparer
  configFilePath: config/fireballComparer.yaml
  programName: FireballComparer
  runText: Run Comparison
  backText: Back to Main Menu

- !!comparer
  configFilePath: config/squadTacticsComparer.yaml
  programName: SquadTacticsComparer
  runText: Run Comparison
  backText: Back to Main Menu

- !!comparer
  configFilePath: config/flightStatsComparer.yaml
  programName: FlightStatsComparer
  runText: Run Comparison
  backText: Back to Main Menu

- !!comparer
  configFilePath: config/timedMissionComparer.yaml
  programName: TimedMissionComparer
  runText: Run Comparison
  backText: Back to Main Menu

- !!comparer
  configFilePath: config/sanctuaryPetTypeComparer.yaml
  programName: SanctuaryPetTypeComparer
  runText: Run Comparison
  backText: Back to Main Menu

- !!comparer
  configFilePath: config/sanctuaryPetSettingsComparer.yaml
  programName: SanctuaryPetSettingsComparer
  runText: Run Comparison
  backText: Back to Main Menu

- !!comparer
  configFilePath: config/chestLocationComparer.yaml
  programName: ChestLocationComparer
  runText: Run Comparison
  backText: Back to Main Menu