#VERY MUCH WIP!

online:
  platform: Steam
  version: 3.10.0
  #if set to true, prints all matching files to a resultFile
  makeFile: true

onlineSourcesConfig:
  baseUrl: http://media.schoolofdragons.com/DWADragonsUnity
  baseUrlSuffix: High
  dataType: xmlFile
  onlineSourceConfig: !!directOnlineSourceConfig
    dataContainer: data/AssetVersionsDO.xml

interpreterConfig:
  #path to the value that will be filtered and listed
  mappingPath: A:@N
  #additional pathConstraints to limit amount of matches
  pathConstraints: []

downloadSettings:
  #if set to true it will wait for user input when a file throws an exception during downloading
  #if set to false it will ignore all failed downloads apart from logging them
  pauseDownloadOnError: True

  #if set to false it won't download the files and instead only log which files it would download
  doDownload: False

resultConfig:
  baseDirectory: fileDownloads\logging

outputDirectory:
  baseDirectory: fileDownloads

  #if set to false it will download directly to the baseDirectory
  #if set to true it will append the platform/version/date as subdirectories
  # example:
  #  platform = true, version = false, date = true
  #  will result in
  #  fileDownloads\Steam\2020.04.07
  appendPlatform: False
  appendVersion: False
  appendDate: False

#use this to filter filenames
#filterexamples:
#  allow al files of any directory with a name starting with "dw" and ending with "do" (e.g. 'RS_SHARED/dwthunderdrumdo')
#    ^(.*?)/dw(.*?)do$
#
#  use multiple regex filters (only allows files that match all filters)
#    regexFilters:
#      - filter1
#      - !filter2
#      - \!filter3
#
#  to negate a regex (allowing only files that don't match it) start the filter with an '!' character (see above)
#  if your regex starts with an '!' for other reasons you can escape the negation by putting a '\' in front of it
regexFilters:
- (RS_SOUND/sndwingflapmed7)|(RS_MOVIES/BoD_Intro.mp4)

#use this to only download some localizations
#otherwise downloads ALL localizations available
#filterexamples:
# allow only en-us and de-de localized files (and files that are not localized)
#   localeFilters:
#     - en-us
#     - de-de
localeFilters:
- en-us
- de-de