sourceConfigHolder:
  lastCreated: fireballHistory\sources\fireball_2021.04.20.txt

  sourceFrom:
    sourceType: lastCreated
    online:
      platform: Steam
      version: 3.8.0
      makeFile: True
      makeLastCreated: False
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07

  sourceTo:
    sourceType: online
    online:
      platform: Steam
      version: 3.15.0
      makeFile: True
      makeLastCreated: True
    local:
      platform: Steam
      version: 3.8.0
      date: 2020.04.07

  onlineSourcesConfig:
    baseUrl: http://media.schoolofdragons.com/DWADragonsUnity
    baseUrlSuffix: High
    dataType: bundleFile

    onlineSourceConfig: !!directOnlineSourceConfig
      dataContainer: data/dragonsres

  localSourcesConfig:
    baseDirectory: fireballHistory\sources
    targetFileName: fireball
    targetFileExtension: txt
    appendPlatform: false
    appendVersion: false
    appendDate: true

resultConfig:
  appendTime: True
  baseDirectory: fireballHistory\results
  makeFile: True
  appendDate: True
  resultFilter: 
    displayAdditions: True
    displayDifferences: True
    displayRemovals: True
    displayCommons: True

onlineSourceInterpreterConfig:
  configPath: _Weapons:Array:data
  
  pathConstraints: []

  mapConfigBy: !!storedMappingValue
    path: _Name
    outputName: Name

  regexTranslator: {}

  typeTranslationDict:
    AmmoType:
      0: Fire
      1: Ice
      2: Electric

  outputNameToTypeDict:
    AmmoType: AmmoType

  configFilter:
  - path: _MinSpeed
    pathType: relative
    doDisplay: True
    outputName: MinSpeed

  - path: _MaxTimeToTarget
    pathType: relative
    doDisplay: True
    outputName: MaxTimeToTarget

  - path: _Damage
    pathType: relative
    doDisplay: True
    outputName: Damage

  - path: _CriticalDamageMultiplier
    pathType: relative
    doDisplay: True
    outputName: CritMultiplier

  - path: _CriticalDamageChance
    pathType: relative
    doDisplay: True
    outputName: CritChance

  - path: _Energy
    pathType: relative
    doDisplay: True
    outputName: Energy

  - path: _TouchRadius
    pathType: relative
    doDisplay: True
    outputName: TouchRadius

  - path: _Lifetime
    pathType: relative
    doDisplay: True
    outputName: Lifetime

  - path: _TotalShots
    pathType: relative
    doDisplay: True
    outputName: TotalShots

  - path: _Cooldown
    pathType: relative
    doDisplay: True
    outputName: Cooldown

  - path: _Range
    pathType: relative
    doDisplay: True
    outputName: Range

  - path: _Homing
    pathType: relative
    doDisplay: True
    outputName: Homing

  - path: _SlowEffect
    pathType: relative
    doDisplay: True
    outputName: SlowEffect

  - path: _AmmoType
    pathType: relative
    doDisplay: True
    outputName: AmmoType

  - path: _RechargeRange:Min
    pathType: relative
    doDisplay: True
    outputName: Recharge:Min

  - path: _RechargeRange:Max
    pathType: relative
    doDisplay: True
    outputName: Recharge:Max

  - path: _AvailableShots
    pathType: relative
    doDisplay: True
    outputName: AvailableShots
